# Building the Image without pushing to confirm it is still buildable
# confirum functionality would unfortunately need way more resources
name: build container image
on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'update-dockerfile'

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
        pip-requirements:
          - requirements-lin-amd.txt
          - requirements-lin-cuda.txt
    runs-on: ubuntu-latest
    name: ${{ matrix.pip-requirements }} ${{ matrix.arch }}
    steps:
      - name: prepare docker-tag
        env:
          repository: ${{ github.repository }}
        run: echo "dockertag=${repository,,}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker-build/Dockerfile
          platforms: Linux/${{ matrix.arch }}
          push: false
          tags: ${{ env.dockertag }}:${{ matrix.pip-requirements }}-${{ matrix.arch }}
          build-args: pip_requirements=${{ matrix.pip-requirements }}
